<?php
$gateProperty=!empty($gateRow['gate_data']);
$gateDetailData=$gateProperty?gateData($gateRow):[];
$gateStatus=$gateProperty?gateEffectiveStatus($gateRow):$gateRow['status'];
$gateScheduleData=$gateDetailData['authorized'] ?? $gateDetailData['requested'] ?? null;
?>
<div class="service-request-heading"><h2><?= $gateProperty?gateNumber((int)$gateRow['id']):'Permit #'.(int)$gateRow['id'] ?></h2><span class="service-status service-status-<?= gateEscape($gateStatus) ?>"><?= gateEscape(ucfirst(str_replace('_',' ',$gateStatus))) ?></span></div>
<p><strong><?= gateEscape($gateRow['permit_type']) ?><?= $gateProperty?' · '.($gateDetailData['direction']==='entry'?'Property Entry (Bring In)':'Property Exit (Pull-Out)'):'' ?></strong></p>
<dl class="permit-identity"><div><dt>Requester</dt><dd><?= gateEscape($gateRow['full_name']) ?></dd></div><div><dt>Unit</dt><dd><?= gateEscape($gateDetailData['unit_number'] ?? $gateRow['unit_number']) ?></dd></div><div><dt>Account ID</dt><dd><?= (int)$gateRow['user_id'] ?></dd></div><div><dt>Contact</dt><dd><?= gateEscape($gateRow['contact_number'] ?: $gateRow['email']) ?></dd></div></dl>
<?php if($gateProperty): ?>
<p>Purpose: <?= gateEscape($gateDetailData['purpose']) ?></p><p><?= nl2br(gateEscape($gateDetailData['description'])) ?></p>
<p>Requested: <?= gateEscape($gateDetailData['requested']['date'].' · '.$gateDetailData['requested']['start'].' – '.$gateDetailData['requested']['end']) ?></p>
<?php if($gateDetailData['authorized']): ?><p><strong>Authorized: <?= gateEscape($gateScheduleData['date'].' · '.$gateScheduleData['start'].' – '.$gateScheduleData['end']) ?></strong> (Asia/Manila)</p><?php endif; ?>
<div class="permit-table-wrap"><table class="permit-table"><thead><tr><th>Item</th><th>Category</th><th>Quantity</th><th>Description</th></tr></thead><tbody><?php foreach(gateChildren($db,(int)$gateRow['id'],'permit_items') as $item): ?><tr><td><?= gateEscape($item['item_name']) ?></td><td><?= gateEscape($item['category']) ?></td><td><?= (int)$item['quantity'] ?></td><td><?= gateEscape($item['description']) ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php foreach(['transporter'=>'Transporter','transporter_contact'=>'Transporter contact','vehicle_plate'=>'Vehicle plate','personnel'=>'Authorized personnel'] as $key=>$label): if(!empty($gateDetailData[$key])): ?><p><?= $label ?>: <?= gateEscape($gateDetailData[$key]) ?></p><?php endif; endforeach; ?>
<?php $gateDocs=gateChildren($db,(int)$gateRow['id'],'permit_documents'); if($gateDocs): ?><h3>Supporting documents</h3><ul><?php foreach($gateDocs as $doc): ?><li><a href="<?= gateEscape(buildUrl('permit_document.php?id='.(int)$doc['id'])) ?>" target="_blank" rel="noopener"><?= gateEscape($doc['original_name']) ?></a></li><?php endforeach; ?></ul><?php endif; ?>
<?php else: ?><p><?= gateEscape($gateRow['start_date'].' to '.$gateRow['end_date']) ?></p><p><?= nl2br(gateEscape($gateRow['details'])) ?></p><?php endif; ?>
<?php if($gateRow['admin_notes']): ?><p><strong>Management remarks:</strong> <?= gateEscape($gateRow['admin_notes']) ?></p><?php endif; ?>
<?php if($gateRow['decided_at']): ?><p>Reviewed by <?= gateEscape($gateRow['approver_name'] ?? 'Management') ?> · <?= gateEscape($gateRow['decided_at']) ?></p><?php endif; ?>
<?php if($gateProperty && isset($gateDetailData['completed_at'])): ?><p>Movement completed: <?= gateEscape($gateDetailData['completed_at']) ?> · Staff account #<?= (int)$gateDetailData['completed_by'] ?></p><?php endif; ?>
<?php if(canReviewPermits() && $gateStatus==='pending'): ?>
<details class="permit-review"><summary>Review this permit</summary><form method="post" class="service-form" data-confirm="Save this permit review decision?">
<?= workflowCsrfField() ?><input type="hidden" name="request_id" value="<?= (int)$gateRow['id'] ?>">
<?php if($gateProperty): ?><input type="hidden" name="action" value="gate_approved"><p class="service-wide">Approval authorizes only the items and schedule shown. Adjust the schedule if needed.</p><label class="field-label">Authorized date<input type="date" name="authorized_date" min="<?= date('Y-m-d') ?>" value="<?= gateEscape($gateScheduleData['date']) ?>" required></label><label class="field-label">Start time<input type="time" name="authorized_start" value="<?= gateEscape($gateScheduleData['start']) ?>" required></label><label class="field-label">End time<input type="time" name="authorized_end" value="<?= gateEscape($gateScheduleData['end']) ?>" required></label><?php endif; ?>
<label class="field-label service-wide">Management remarks (required for rejection / changes)<textarea name="admin_notes" maxlength="500" rows="3"></textarea></label>
<div class="service-wide service-actions"><?php if($gateProperty): ?><button name="action" value="gate_approved" class="service-btn service-btn-approve">Approve</button><button name="action" value="gate_rejected" class="service-btn service-btn-danger" formnovalidate>Reject</button><button name="action" value="gate_changes_requested" class="service-btn service-btn-secondary" formnovalidate>Request changes</button><?php else: ?><button name="decision" value="approved" class="service-btn service-btn-approve">Approve</button><button name="decision" value="rejected" class="service-btn service-btn-danger">Reject</button><?php endif; ?></div></form></details><?php endif; ?>
<?php if($gateProperty && gateValid($gateRow) && (isSecurity() || canReviewPermits())): ?>
<form method="post" class="service-form permit-completion" data-confirm="Confirm that all listed items have been physically checked and moved? This pass cannot be reused."><?= workflowCsrfField() ?><input type="hidden" name="request_id" value="<?= (int)$gateRow['id'] ?>"><input type="hidden" name="action" value="gate_completed"><label class="checkbox service-wide"><input type="checkbox" name="physical_check" value="1" required> I physically checked the items and confirm the movement.</label><label class="field-label service-wide">Verification remarks (optional)<textarea name="admin_notes" maxlength="500" rows="2"></textarea></label><button class="service-btn service-btn-approve">Confirm movement completed</button></form>
<?php endif; ?>
<?php if($gateProperty): ?><details class="permit-review"><summary>Request and verification history</summary><ol class="permit-history-list"><?php foreach(gateChildren($db,(int)$gateRow['id'],'permit_history') as $event): ?><li><strong><?= gateEscape(ucfirst(str_replace('_',' ',$event['action']))) ?></strong> · <?= gateEscape($event['created_at']) ?> · <?= gateEscape($event['actor_name'] ?? 'Staff') ?><?php if($event['remarks']): ?><p><?= gateEscape($event['remarks']) ?></p><?php endif; ?></li><?php endforeach; ?><?php if($gateStatus==='expired'): ?><li>Expired at the end of the authorized schedule.</li><?php endif; ?></ol></details><?php endif; ?>
