<?php
/** Dompdf report authoring uses the exact same prepared filters as history. */
function qrReportData(mysqli $db,array $filters): array {
    if(!$filters['dates']['from']) throw new InvalidArgumentException('Select a single date, date range or preset for the report.');
    $days=(new DateTimeImmutable($filters['dates']['start']))->diff(new DateTimeImmutable($filters['dates']['end']))->days;
    if($days>365) throw new InvalidArgumentException('Choose a report period of at most 366 days.');
    $db->query('START TRANSACTION WITH CONSISTENT SNAPSHOT');
    try {
        $summary=qrSummary($db,$filters);
        if(!$summary['total']) throw new InvalidArgumentException('No scans match this report. Choose another period or filter.');
        if($summary['total']>2000) throw new InvalidArgumentException('This report exceeds 2,000 records. Narrow the period or filters.');
        [$where,$types,$params]=qrWhere($filters); $order=$filters['sort']==='oldest'?'ASC':'DESC';
        $rows=qrQuery($db,"SELECT * FROM qr_scan_logs$where ORDER BY event_time_utc $order,id $order LIMIT 2000",$types,$params)->fetch_all(MYSQLI_ASSOC);
        $db->commit(); return ['summary'=>$summary,'rows'=>array_map('qrPublicRecord',$rows)];
    } catch(Throwable $e) { $db->rollback(); throw $e; }
}
function qrReportHtml(array $report,array $filters,array $scanner,string $reference,string $generated): string {
    $e=static fn($value)=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8'); $s=$report['summary'];
    $filterLabels='Type: '.($filters['qr_type'] ?: 'All').' | Status: '.($filters['status'] ?: 'All').' | Scanner role: '.($filters['role'] ?: 'All').' | Search: '.($filters['q'] ?: 'None');
    $html='<!doctype html><html><head><meta charset="utf-8"><style>@page{margin:30px 28px 42px}body{font-family:DejaVu Sans,sans-serif;font-size:8px;color:#172033}h1{font-size:19px;margin:0 0 4px;color:#172033}h2{font-size:13px;margin:0 0 14px;color:#a45b07}.meta{line-height:1.7;margin-bottom:12px}.summary{width:100%;border-collapse:collapse;margin:12px 0 16px}.summary td{padding:9px;background:#f1f5f9;border:1px solid #cbd5e1;font-size:9px}.summary strong{display:block;font-size:15px}table.records{border-collapse:collapse;width:100%;table-layout:fixed}thead{display:table-header-group}tr{page-break-inside:avoid}.records th,.records td{border:1px solid #cbd5e1;padding:5px 4px;vertical-align:top;word-wrap:break-word;line-height:1.45}.records th{background:#e8edf3;font-size:7.5px}.records tbody tr:nth-child(even){background:#f8fafc}.note{font-size:8px;color:#475569}</style></head><body><h1>THE CELANDINE HOMES</h1><h2>QR SCAN HISTORY REPORT</h2><div class="meta"><strong>Selected period:</strong> '.$e($filters['dates']['start']).' to '.$e($filters['dates']['end']).' (Asia/Manila, both dates included)<br><strong>Generated:</strong> '.$e($generated).' Asia/Manila<br><strong>Generated by:</strong> '.$e($scanner['name']).' ('.$e(ucfirst($scanner['role'])).')<br><strong>Report reference:</strong> '.$e($reference).'<br>'.$e($filterLabels).'</div><table class="summary"><tr>';
    foreach(['total'=>'Total scans','valid'=>'Valid','invalid'=>'Invalid / Already Used','expired_cancelled'=>'Expired / Cancelled','visitor'=>'Visitor','property'=>'Property Gate Pass'] as $key=>$label) $html.='<td>'.$e($label).'<strong>'.$s[$key].'</strong></td>';
    $html.='</tr></table><table class="records"><thead><tr><th style="width:7%">Scan ID</th><th style="width:9%">QR Type</th><th style="width:15%">Visitor / Requester</th><th style="width:5%">Unit</th><th style="width:12%">Pass / Permit</th><th style="width:10%">Scan date</th><th style="width:8%">Scan time</th><th style="width:10%">Action</th><th style="width:9%">Result</th><th style="width:15%">Scanned by</th></tr></thead><tbody>';
    foreach($report['rows'] as $row) {
        $values=[$row['scan_reference'],match($row['qr_type']){'property'=>'Property Gate Pass','visitor'=>'Visitor QR Pass','parking'=>'Visitor Parking',default=>ucfirst($row['qr_type'])},$row['subject_name'] ?: $row['requester_name'] ?: 'Unknown',$row['unit_number'] ?: '-', $row['pass_number'] ?: '-',substr($row['local_time'],0,10),substr($row['local_time'],11),ucfirst(str_replace('_',' ',$row['scan_action'])),ucfirst(str_replace('_',' ',$row['verification_result'])),$row['scanner_full_name'].' ('.ucfirst($row['scanner_role']).')'];
        $html.='<tr>'; foreach($values as $value) $html.='<td>'.$e($value).'</td>'; $html.='</tr>';
    }
    return $html.'</tbody></table><p class="note">Verification events and confirmed movements are separate records. Historical outcomes are snapshots; a valid scan alone does not authorize a repeated movement. Legacy records with unavailable outcomes are labeled Unknown.</p></body></html>';
}
function qrReportPdf(array $report,array $filters,array $scanner): string {
    $reference='QRR-'.gmdate('Ymd-His').'-'.strtoupper(bin2hex(random_bytes(3)));
    $generated=(new DateTimeImmutable('now',new DateTimeZone('Asia/Manila')))->format('Y-m-d H:i:s');
    $options=new Dompdf\Options(); $options->set('isRemoteEnabled',false); $options->set('isJavascriptEnabled',false); $options->set('isPhpEnabled',false);
    $pdf=new Dompdf\Dompdf($options); $pdf->setPaper('A4','landscape'); $pdf->loadHtml(qrReportHtml($report,$filters,$scanner,$reference,$generated),'UTF-8'); $pdf->render();
    $pdf->getCanvas()->page_text(28,570,$reference.' | Generated '.$generated.' Asia/Manila | Page {PAGE_NUM} of {PAGE_COUNT}',$pdf->getFontMetrics()->getFont('Helvetica'),7,[.25,.3,.35]);
    return $pdf->output();
}
