<?php
function renderQrFilters(string $prefix,bool $export=false): void {
?>
<label>Search<input type="search" name="q" maxlength="120" placeholder="Name, unit, pass, scan ID or scanner" id="<?= $prefix ?>Search"></label>
<label>QR type<select name="qr_type"><option value="">All types</option><option value="visitor">Visitor QR Pass</option><option value="property">Property Gate Pass</option><option value="parking">Visitor Parking</option><option value="permit">Other Permit</option><option value="unknown">Unknown QR</option></select></label>
<label>Verification status<select name="status"><option value="">All statuses</option><?php foreach(['valid','invalid','expired','cancelled','already_used','unknown'] as $value): ?><option value="<?= $value ?>"><?= ucfirst(str_replace('_',' ',$value)) ?></option><?php endforeach; ?></select></label>
<label>Scanner role<select name="role"><option value="">All roles</option><option value="security">Security</option><option value="admin">Admin</option><option value="superadmin">Superadmin</option></select></label>
<label>Date period<select name="period" class="qr-period"><?php if(!$export): ?><option value="all">All dates</option><?php endif; ?><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="last7">Last 7 days</option><option value="month">This month</option><option value="single">Single date</option><option value="range">Custom date range</option></select></label>
<label class="qr-date-single" hidden>Selected date<input type="date" name="date" value="<?= date('Y-m-d') ?>"></label>
<label class="qr-date-range" hidden>Start date<input type="date" name="start_date" value="<?= date('Y-m-d') ?>"></label><label class="qr-date-range" hidden>End date<input type="date" name="end_date" value="<?= date('Y-m-d') ?>"></label>
<label>Sort<select name="sort"><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></label>
<?php } ?>
<section class="admin-panel scanner-history-panel" id="historyPanel" hidden role="tabpanel" aria-labelledby="historyTab">
<div class="scanner-history-heading"><div><h2>Scan History</h2><p>Verification attempts and confirmed movements · Asia/Manila</p></div><div class="qr-history-actions"><button type="button" id="refreshHistory" class="service-btn service-btn-secondary">Refresh</button><?php if(qrExportAllowed()): ?><button type="button" id="openQrExport" class="service-btn">Export to PDF</button><?php endif; ?></div></div>
<div class="qr-summary" aria-live="polite"><?php foreach(['total'=>'Total scans','valid'=>'Valid scans','invalid'=>'Invalid / Already Used','expired_cancelled'=>'Expired / Cancelled'] as $key=>$label): ?><div><span><?= $label ?></span><strong id="qrSummary_<?= $key ?>">0</strong></div><?php endforeach; ?></div>
<div class="qr-filter-section"><h3>Find a scan</h3><p>Search by visitor, requester, unit, pass number, scan ID or staff member. Summary counts reflect your current filters.</p><form id="qrHistoryFilters" class="qr-filter-form"><?php renderQrFilters('history'); ?><div class="qr-filter-actions"><button class="service-btn" type="submit">Apply filters</button><button class="service-btn service-btn-secondary" type="button" id="clearQrSearch">Clear search</button><button class="service-btn service-btn-secondary" type="reset">Reset filters</button></div></form></div>
<p id="qrHistoryFeedback" role="status" aria-live="polite"></p>
<div class="scanner-records-heading"><h3>Scan records</h3><p id="qrTableHint">Scroll horizontally to view all columns. Times are in Asia/Manila.</p></div>
<div class="scanner-history-wrap" role="region" aria-label="Scan history records" aria-describedby="qrTableHint" tabindex="0"><table class="scanner-history-table" aria-label="Verification attempts and confirmed gate movements"><thead><tr><th scope="col">Scan ID</th><th scope="col">QR type</th><th scope="col">Visitor / Requester</th><th scope="col">Unit</th><th scope="col">Pass / Permit</th><th scope="col">Scan date and time</th><th scope="col">Scanned by</th><th scope="col">Role</th><th scope="col">Action</th><th scope="col">Status</th><th scope="col">Actions</th></tr></thead><tbody id="scanHistoryBody"><tr><td colspan="11" class="qr-table-message">Loading scan history…</td></tr></tbody></table></div>
<div class="qr-pagination"><span id="qrMatchCount">0 matching records</span><div><button type="button" id="qrPrevious" class="service-btn service-btn-secondary" disabled>Previous</button><span id="qrPageNumber">Page 1 of 1</span><button type="button" id="qrNext" class="service-btn service-btn-secondary" disabled>Next</button></div></div>
</section>
<dialog id="qrScanDetails" class="qr-dialog" aria-labelledby="qrDetailsTitle"><div class="qr-dialog-heading"><h2 id="qrDetailsTitle">Scan details</h2><button class="service-btn service-btn-secondary" type="button" data-close-dialog>Close</button></div><dl id="qrDetailsFields" class="qr-detail-fields"></dl></dialog>
<?php if(qrExportAllowed()): ?><dialog id="qrExportDialog" class="qr-dialog" aria-labelledby="qrExportTitle"><div class="qr-dialog-heading"><h2 id="qrExportTitle">Export scan history</h2><button class="service-btn service-btn-secondary" type="button" data-close-dialog>Close</button></div><p>Select the report period in Asia/Manila. The entire selected end date is included.</p>
<form id="qrExportForm" class="qr-filter-form"><?php renderQrFilters('export',true); ?><label class="qr-use-active"><input type="checkbox" id="qrUseActive" checked> Use active search, type, status and role filters</label><p class="qr-export-note">Reports include all matching pages, up to 2,000 records and 366 days.</p><p id="qrExportFeedback" class="qr-export-note" role="status" aria-live="polite"></p><div class="qr-filter-actions"><button class="service-btn" type="submit" id="qrDownloadPdf">Download PDF</button><button class="service-btn service-btn-secondary" type="button" data-close-dialog>Cancel</button></div></form></dialog><?php endif; ?>
