<?php
if (!residentHasPermission('resident.stickers.order')) {
    echo '<section class="payment-methods-card" id="residentSticker"><h3 class="section-title">Unit Owner Services</h3><p class="amenity-desc">Paid parking stickers and their billing are managed by the unit owner. You can register your own vehicle and request temporary visitor parking when those services are enabled.</p></section>';
    return;
}
$canOrderStickers = !$latestStickerOrder || $latestStickerOrder['claim_status'] === 'issued' || $latestStickerOrder['status'] === 'cancelled';
$selectedStickerVehicles = is_array($_POST['vehicle_ids'] ?? null) ? array_map('intval',$_POST['vehicle_ids']) : [(int)($_GET['vehicle_id'] ?? 0)];
?>
<section class="payment-methods-card" id="residentSticker">
<div class="service-request-heading"><h3 class="section-title">Resident Parking Stickers</h3><?php if (residentHasPermission('resident.vehicles.register')): ?><a class="service-btn service-btn-secondary" href="vehicles.php"><?php echo systemSidebarIcon('parking'); ?> Registered vehicles</a><?php endif; ?></div>
<p class="amenity-desc">Request one sticker per approved vehicle registered to you or an approved resident linked to your unit. Your owner account receives and pays the sticker bill. Price: <strong>₱<?php echo number_format((float)$parkingPolicy['sticker_price'],2); ?></strong> per sticker. Visitor parking uses temporary passes.</p>
<?php if ($latestStickerOrder): ?><div class="sticker-order-summary"><strong>Order #<?php echo (int)$latestStickerOrder['id']; ?></strong><span><?php echo (int)$latestStickerOrder['quantity']; ?> sticker(s) · ₱<?php echo number_format((float)$latestStickerOrder['amount'],2); ?></span>
<?php foreach($latestStickerVehicles as $vehicle): ?><p><?php echo htmlspecialchars($vehicle['plate_number'].' · '.$vehicle['make'].' '.$vehicle['model']); ?><?php if($vehicle['sticker_number']): ?> · <strong><?php echo htmlspecialchars($vehicle['sticker_number']); ?></strong><?php endif; ?></p><?php endforeach; ?>
<?php if ($latestStickerOrder['claim_status']==='issued'): ?><p>Issued<?php echo $latestStickerOrder['issued_at']?' on '.htmlspecialchars(date('M j, Y',strtotime($latestStickerOrder['issued_at']))):''; ?>.<?php if(!$latestStickerVehicles): ?> This historical order needs a vehicle link; contact management after registering your vehicle.<?php endif; ?></p>
<?php elseif($latestStickerOrder['bill_status']==='paid'): ?><p>Payment verified. Visit management with your receipt to claim your sticker. Issuance is recorded against your approved vehicle.</p>
<?php else: ?><p>Awaiting verified payment. Complete payment from Billing &amp; Payments.</p><a class="service-btn" href="payments.php">Go to billing &amp; payments</a><?php endif; ?></div><?php endif; ?>
<?php if($canOrderStickers): ?>
<?php if(!$eligibleStickerVehicles): ?><div class="service-empty-state"><p>No approved vehicles are available for a new sticker. Register a vehicle or check its review and sticker status.</p><a class="service-btn" href="vehicles.php">Register or manage vehicles</a></div>
<?php else: ?><form method="post" action="parking.php#residentSticker" id="stickerOrderForm"><?php echo workflowCsrfField(); ?><input type="hidden" name="form_action" value="buy_sticker"><fieldset class="sticker-vehicle-picker"><legend>Select approved vehicles</legend><?php foreach($eligibleStickerVehicles as $vehicle): ?><label class="checkbox sticker-vehicle-option"><input type="checkbox" name="vehicle_ids[]" value="<?php echo (int)$vehicle['id']; ?>" <?php echo in_array((int)$vehicle['id'],$selectedStickerVehicles,true)?'checked':''; ?>><span><strong><?php echo htmlspecialchars($vehicle['plate_number']); ?></strong><small><?php echo htmlspecialchars($vehicle['make'].' '.$vehicle['model'].' · '.$vehicle['color']); ?><?php if ((int)$vehicle['user_id'] !== (int)$_SESSION['user_id']): ?> · Linked resident vehicle<?php endif; ?></small></span></label><?php endforeach; ?></fieldset><p class="amenity-desc">Up to <?php echo (int)$parkingPolicy['sticker_max_quantity']; ?> vehicles per order. Total: <strong>₱<span id="stickerOrderTotal" data-unit-price="<?php echo (float)$parkingPolicy['sticker_price']; ?>" data-max-quantity="<?php echo (int)$parkingPolicy['sticker_max_quantity']; ?>">0.00</span></strong></p><button class="service-btn" type="submit" id="submitStickerOrder">Request stickers &amp; create bill</button></form><?php endif; ?>
<?php endif; ?></section>
